name: deploy rules

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: Project build in ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      # Sets up Java version
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: '8'
      # Sets up Maven version
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.6.3
      # Checks Java version
      - name: Check Java version
        run: java -version
      # Checks Maven version
      - name: Check Maven version
        run: mvn -version
      - name: Compile, test, and package the project
        run: mvn -f JavaCryptographicArchitecture -B clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

